/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javacard;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author huyho
 */
public class login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pin = new javax.swing.JPasswordField();
        confirmBtn = new javax.swing.JButton();
        btnRegisterLink = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NHẬP MÃ PIN");

        jLabel2.setText("PIN");

        pin.setText("jPasswordField1");
        pin.addActionListener(this::pinActionPerformed);

        confirmBtn.setText("XÁC NHẬN");
        confirmBtn.addActionListener(this::confirmBtnActionPerformed);

        btnRegisterLink.setText("ĐĂNG KÝ");
        btnRegisterLink.addActionListener(this::btnRegisterLinkActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegisterLink)
                        .addGap(96, 96, 96)
                        .addComponent(confirmBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(232, 232, 232)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(btnRegisterLink))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }

    private void performLogin() {
        String inputPin = new String(pin.getPassword());

        if (inputPin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã PIN!");
            return;
        }

        SmartCardWork card = new SmartCardWork();

        // 1. Kết nối thẻ
        if (card.connectCard()) {

            // 2. Gọi hàm verifyPin mới (nhận về mã SW)
            int sw = card.verifyPin(inputPin);

            if (sw == 0x9000) {
                // -- PIN ĐÚNG --
                // Lấy ID thẻ để gọi Backend
                String cardId = card.getCardID();

                if (cardId != null) {
                    APIService api = new APIService();
                    APIService.CardResponse cardInfo = api.getCardInfo(cardId);

                    if (cardInfo != null) {
                        this.dispose();
                        new viewInfo(cardInfo).setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Thẻ hợp lệ nhưng không tìm thấy dữ liệu trên Server!", "Lỗi Backend", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không đọc được ID thẻ! (Thẻ chưa khởi tạo)", "Lỗi Thẻ", JOptionPane.ERROR_MESSAGE);
                }

            } else if (sw == 0x6983) {
                // -- THẺ BỊ KHÓA --
                JOptionPane.showMessageDialog(this, "Thẻ đã bị KHÓA do nhập sai quá số lần quy định!\nVui lòng nhấn nút RESET để mở khóa.", "Thẻ bị khóa", JOptionPane.ERROR_MESSAGE);

            } else if ((sw & 0xFFF0) == 0x63C0) {
                // -- SAI PIN (Vẫn còn lượt thử) --
                // 0x63Cx -> x là số lần còn lại
                int retries = sw & 0x0F;
                JOptionPane.showMessageDialog(this, "Sai mã PIN!\nSố lần thử còn lại: " + retries, "Cảnh báo", JOptionPane.WARNING_MESSAGE);

            } else {
                // -- LỖI KHÁC --
                JOptionPane.showMessageDialog(this, "Lỗi xác thực không xác định: 0x" + Integer.toHexString(sw).toUpperCase(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

            // Ngắt kết nối sau khi xử lý xong
            card.disconnect();

        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thẻ! Vui lòng kiểm tra đầu đọc.", "Lỗi kết nối", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
        performLogin();
    }

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:\
        performLogin();

    }

    private void btnRegisterLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterLinkActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Đóng form Login
        new register().setVisible(true); // Mở form Đăng ký
    }//GEN-LAST:event_btnRegisterLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterLink;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pin;
    // End of variables declaration//GEN-END:variables
}
