/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javacard;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author huyho
 */
public class viewInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewInfo.class.getName());

    /**
     * Creates new form viewInfo
     */
    public viewInfo(APIService.CardResponse cardData) {
        initComponents();

        // Hiển thị dữ liệu lên các ô Text Field
        if (cardData != null && cardData.user != null) {
            fullName.setText(cardData.user.fullName);
            phoneNumber.setText(cardData.user.phone);
            province.setText(cardData.user.address);

            // Xử lý ngày sinh (Backend trả về yyyy-MM-dd, ta có thể format lại nếu muốn)
            dateOfBirth.setText(cardData.user.dob);
//            email.setText(cardData.user.email);


            // Hiển thị thêm điểm tích lũy
            // txtPoint.setText(String.valueOf(cardData.pointBalance));
        }
        hienThiThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fullName = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        province = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        endBtn = new javax.swing.JButton();
        changePinBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("THÔNG TIN THÀNH VIÊN");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Ngày sinh: ");

        jLabel4.setText("Quê quán:");

        jLabel5.setText("Số điện thoại:");

        endBtn.setText("XÁC NHẬN");
        endBtn.addActionListener(this::endBtnActionPerformed);

        changePinBtn.setText("ĐỔI MÃ PIN");
        changePinBtn.addActionListener(this::changePinBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(changePinBtn)
                        .addGap(92, 92, 92)
                        .addComponent(endBtn)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateOfBirth, fullName, phoneNumber, province});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateOfBirth))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endBtn)
                    .addComponent(changePinBtn))
                .addGap(34, 34, 34))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateOfBirth, fullName, phoneNumber, province});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void changePinBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // 1. Yêu cầu nhập PIN mới qua InputDialog
        String newPin = javax.swing.JOptionPane.showInputDialog(this, "Nhập mã PIN mới (6 số):");

        if (newPin == null || newPin.isEmpty()) return; // Người dùng ấn Cancel

        if (newPin.length() != 6) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã PIN phải có 6 ký tự!");
            return;
        }

        // 2. Gọi lệnh đổi PIN
        SmartCardWork card = new SmartCardWork();
        if (card.connectCard()) {
            // Lưu ý: Để đổi PIN, thẻ yêu cầu phải Verify PIN cũ trước.
            // Trong phiên làm việc này, nếu applet chưa "quên" trạng thái đã verify thì ok.
            // Nhưng an toàn nhất là yêu cầu nhập lại PIN cũ để xác thực rồi mới đổi.

            // (Cách đơn giản cho demo: Giả sử User vừa Login xong, thẻ vẫn đang nhớ trạng thái Validated)
            if (card.changePin(newPin)) {
                 javax.swing.JOptionPane.showMessageDialog(this, "Đổi PIN thành công!");
            } else {
                 javax.swing.JOptionPane.showMessageDialog(this, "Đổi PIN thất bại! (Có thể do chưa xác thực PIN cũ)");
            }
            card.disconnect();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi kết nối thẻ!");
        }
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new viewInfo().setVisible(true));
//    }

    private void hienThiThongTin() {
        SmartCardWork card = new SmartCardWork();
        if (card.connectCard()) {
            // Lấy chuỗi data dạng "Ten|NgaySinh|Que|SDT"
            String data = card.getUserInfo();

            if (data != null && !data.isEmpty()) {
                // Tách chuỗi bằng dấu "|"
                String[] parts = data.split("\\|");

                if (parts.length >= 4) {
                    fullName.setText(parts[0]);
                    dateOfBirth.setText(parts[1]);
                    province.setText(parts[2]);
                    phoneNumber.setText(parts[3]);
                }
            }
            card.disconnect();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi kết nối thẻ khi lấy thông tin!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePinBtn;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton endBtn;
    private javax.swing.JTextField fullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField province;
    private javax.swing.JTextField email;
    // End of variables declaration//GEN-END:variables
}
